#  NumPy

In [5]:
import numpy as np

In [7]:
L1 = [1,2,3,4,5] # Crear una lista

In [8]:
x1 = np.array(L1)

In [9]:
x1

array([1, 2, 3, 4, 5])

In [25]:
x2 = np.array(L1, dtype = "float32")

In [26]:
x2

array([1., 2., 3., 4., 5.], dtype=float32)

Tipos de dtype
- bool_ 
- int_, intc, intp, int8, int16, int32, int64
- uint, uint8, uint16, uint32, uint64
- float_, float16, float32, float64
- complex_, complex64, complex128

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(3,12,dtype=float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [33]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [34]:
np.linspace(1,7,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [35]:
np.eye(5) # CRear una matriz de identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
x = np.zeros((8,3))

In [37]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
x.reshape(6,4) #cambiamos el aspecto de la matriz x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
x = np.arange(24)

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
x.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [52]:
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [54]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.ravel(x) # De una matriz la convierte en una lista

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

La diferencia entre `np.ravel(x)` y `x.flatten()` es que la segunda funcion crea una copia del original miesntras que la otra esta transformando

In [57]:
np.transpose(x) # Transponemos una matriz

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [58]:
np.resize(x, (5,3)) #CRea una matriz de una dimension especifica y si el tamaño no es acorde al numero de datos. La completa
                    # repitiendo la secuencia

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios

#### 1. Crear un array de datos con valores entre 5 y 120

In [83]:
x = np.arange(5,121)
x

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

##### 2. Crear una matriz 4x4 con los valores desde 0 hasta 15

In [84]:
x = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### 3. Crear una identidad 7x7

In [85]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

##### 4. Crear un array de 20 elementos y transformarlos en una matriz 5x4

In [86]:
x = np.linspace(10,20,20)
x.reshape(5,4)

array([[10.        , 10.52631579, 11.05263158, 11.57894737],
       [12.10526316, 12.63157895, 13.15789474, 13.68421053],
       [14.21052632, 14.73684211, 15.26315789, 15.78947368],
       [16.31578947, 16.84210526, 17.36842105, 17.89473684],
       [18.42105263, 18.94736842, 19.47368421, 20.        ]])

#### 5. Crear un array con 20 numeros con los valores entre 0 y 5 espaciados de forma uniforme

In [87]:
x = np.linspace(0,5,20)
x

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

#  Propiedades de los arrays

In [90]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
x.ndim # Cuantas dimensiones tiene el array

2

In [92]:
x.shape # Como son esas dos dimensiones

(3, 4)

In [93]:
x.size # Numero total de elementos de la matriz

12

In [94]:
x.dtype # Tipo de datos de la matriz

dtype('int32')

In [101]:
x.itemsize # Muestra el tamaño en bytes de cada elemento de la matriz

4

In [102]:
x.data # Muestra donde esta ubicada el array en la memoria

In [104]:
x[2] 

array([ 8,  9, 10, 11])

In [105]:
x[2,1]

9

In [107]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [108]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [110]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [111]:
y[2]

2

In [112]:
y[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [113]:
y[1:8:2]

array([1, 3, 5, 7])

In [131]:
z = np.arange(10,6,-1)
z

array([10,  9,  8,  7])

In [132]:
y[z]

array([10,  9,  8,  7])

In [134]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [135]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [137]:
cond = (x>30) 
cond

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [138]:
x[cond]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [140]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [142]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [143]:
x.dtype

dtype('int32')

In [145]:
x[5] = 3.1415
x # El reemplazo solo muestra la parte entera de 3.1415 ya que con x.dtype podemos ver que los elementos son enteros

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [172]:
a = np.eye(8)
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [175]:
a[:,0:8:7] = 4 # Estamos cogiendo la columna 0 y 8 de 7 en 7
a[0:8:7] = 2 # Estamos cogiendo la fila 0 y 8 de 7 en 7
a

array([[2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 1., 0., 0., 0., 0., 0., 4.],
       [4., 0., 1., 0., 0., 0., 0., 4.],
       [4., 0., 0., 1., 0., 0., 0., 4.],
       [4., 0., 0., 0., 1., 0., 0., 4.],
       [4., 0., 0., 0., 0., 1., 0., 4.],
       [4., 0., 0., 0., 0., 0., 1., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2.]])